name: SonarQube Analysis and Quality Gate

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      run: |
        mvn clean verify sonar:sonar \
          -Dsonar.login=${SONAR_TOKEN} \
          -Dsonar.projectKey=sonar-action

    - name: SonarQube Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      with:
        projectKey: 'sonar-action'
