name: Test My Reusable Workflow
on: push

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: CICD-test-nable/JAVA_SAMPLE_SPRING/.github/workflows/main.yml@master
      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}


# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Use the reusable workflow from repository A
#       - name: Use Reusable Workflow from A
#         uses: CICD-test-nable/JAVA_SAMPLE_SPRING/.github/workflows/main.yml@master
